<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Local Debug</Configurations>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Local Debug' ">
    <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
    <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
    <DefineConstants>TRACE;DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\C64AssemblerStudio.Core\C64AssemblerStudio.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(Configuration)' == 'Local Debug' ">
    <ProjectReference Include="..\..\..\..\retro-dbg-data-provider\src\Righthand.RetroDbgDataProvider\Righthand.RetroDbgDataProvider\Righthand.RetroDbgDataProvider.csproj" />
    <ProjectReference Include="..\..\..\..\vice-bridge-net\source\ViceMonitor.Bridge\Righthand.ViceMonitor.Bridge\Righthand.ViceMonitor.Bridge.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)' != 'Local Debug' ">
    <PackageReference Include="Retro.Debug.Data.Provider"/>
    <PackageReference Include="Righthand.Vice.Bridge" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Collections.Immutable" />
    <Using Include="System.Collections.ObjectModel" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Test</_Parameter1>
      <!-- We use the value of AssemblyName to declare the value of the attribute -->
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="Dock.Serializer" />
    <PackageReference Include="FuzzySharp" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="PropertyChanged.Fody" PrivateAssets="All" />
    <PackageReference Include="Righthand.MessageBus" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\main.template" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Grammars\BreakpointConditions\gen\" />
  </ItemGroup>
</Project>
