<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Local Debug</Configurations>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Local Debug' ">
      <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
      <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="AutoFixture.AutoNSubstitute" />
        <PackageReference Include="AutoFixture.Community.ImmutableCollections" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NLog.Extensions.Logging" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>
    <ItemGroup Condition=" '$(Configuration)' == 'Local Debug' ">
        <ProjectReference Include="..\..\..\..\..\retro-dbg-data-provider\src\Righthand.RetroDbgDataProvider\Righthand.RetroDbgDataProvider\Righthand.RetroDbgDataProvider.csproj" />
    </ItemGroup>
    <ItemGroup Condition=" '$(Configuration)' != 'Local Debug' ">
        <PackageReference Include="Retro.Debug.Data.Provider" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\C64AssemblerStudio.Core\C64AssemblerStudio.Core.csproj" />
      <ProjectReference Include="..\..\C64AssemblerStudio.Engine\C64AssemblerStudio.Engine.csproj" />
      <ProjectReference Include="..\TestsBase\TestsBase.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="TestFileSystems\Default\Libraries\One\one_main.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Libraries\One\Sub\InnerSubOne\inner_sub_one.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Libraries\One\Sub\one_sub.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Libraries\Two\two_main.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Project\main.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Project\Sub\Nested\xfile.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="TestFileSystems\Default\Project\Sub\sub.asm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
