<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <Using Include="Cake.Frosting" />
        <Using Include="Cake.Core" />
        <Using Include="Cake.Common" />
        <Using Include="Cake.Common.Diagnostics" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Cake.Flatpak" Version="1.1.2" />
        <PackageReference Include="Cake.Frosting" Version="6.2.0" />
    </ItemGroup>
</Project>